# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_ftrans <- function(A) {
    .Call('walkr_rcppeigen_ftrans', PACKAGE = 'walkr', A)
}

rcppeigen_fsolve <- function(A) {
    .Call('walkr_rcppeigen_fsolve', PACKAGE = 'walkr', A)
}

rcppeigen_fdet <- function(A) {
    .Call('walkr_rcppeigen_fdet', PACKAGE = 'walkr', A)
}

rcppeigen_fprod <- function(A, B) {
    .Call('walkr_rcppeigen_fprod', PACKAGE = 'walkr', A, B)
}

rcppeigen_fcrossprod <- function(A, B) {
    .Call('walkr_rcppeigen_fcrossprod', PACKAGE = 'walkr', A, B)
}

rcppeigen_ftcrossprod <- function(A, B) {
    .Call('walkr_rcppeigen_ftcrossprod', PACKAGE = 'walkr', A, B)
}

