# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('walkr_rcppeigen_hello_world', PACKAGE = 'walkr')
}

rcppeigen_outerproduct <- function(x) {
    .Call('walkr_rcppeigen_outerproduct', PACKAGE = 'walkr', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('walkr_rcppeigen_innerproduct', PACKAGE = 'walkr', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('walkr_rcppeigen_bothproducts', PACKAGE = 'walkr', x)
}

rcppeigen_ftrans <- function(A) {
    .Call('walkr_rcppeigen_ftrans', PACKAGE = 'walkr', A)
}

rcppeigen_fsolve <- function(A) {
    .Call('walkr_rcppeigen_fsolve', PACKAGE = 'walkr', A)
}

rcppeigen_fdet <- function(A) {
    .Call('walkr_rcppeigen_fdet', PACKAGE = 'walkr', A)
}

